// AIM NOW wordmark — exact brand artwork with a transparent background.
// Generated by scripts/make-logo-svg.js (navy keyed out, glow preserved).

export default function Logo({ className = 'h-8 w-auto' }) {
  return (
    <img
      src="/aimnow.svg"
      alt="AIM NOW"
      className={className}
      width={680}
      height={248}
      decoding="async"
    />
  )
}

// Circuit-node icon mark — used in compact contexts (PWA install banner).
export function LogoMark({ className = '' }) {
  return (
    <svg viewBox="0 0 64 64" className={className} fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <defs>
        <linearGradient id="aimGrad" x1="0" y1="0" x2="64" y2="64" gradientUnits="userSpaceOnUse">
          <stop stopColor="#5fd0ff" />
          <stop offset="1" stopColor="#2b8cff" />
        </linearGradient>
        <filter id="aimGlow" x="-50%" y="-50%" width="200%" height="200%">
          <feGaussianBlur stdDeviation="2" result="b" />
          <feMerge>
            <feMergeNode in="b" />
            <feMergeNode in="SourceGraphic" />
          </feMerge>
        </filter>
      </defs>
      <rect x="2" y="2" width="60" height="60" rx="14" stroke="url(#aimGrad)" strokeWidth="2.5" opacity="0.5" />
      <g filter="url(#aimGlow)" stroke="url(#aimGrad)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
        {/* stylized 'A' / arrow-up = AIM */}
        <path d="M20 46 L32 18 L44 46" />
        <path d="M25 36 H39" />
      </g>
      {/* circuit nodes */}
      <circle cx="32" cy="18" r="3.5" fill="#5fd0ff" filter="url(#aimGlow)" />
      <circle cx="20" cy="46" r="3" fill="#2b8cff" />
      <circle cx="44" cy="46" r="3" fill="#2b8cff" />
      <path d="M44 46 H54 M10 46 H20" stroke="url(#aimGrad)" strokeWidth="2" strokeLinecap="round" opacity="0.7" />
    </svg>
  )
}
