// AIM NOW wordmark — exact brand artwork with a transparent background.
// Generated by scripts/make-logo-svg.js (navy keyed out, glow preserved).

export default function Logo({ className = 'h-8 w-auto' }) {
  return (
    <img
      src="/aimnow.svg"
      alt="AIM NOW"
      className={`block max-w-none ${className}`}
      width={1000}
      height={139}
      style={{ aspectRatio: '1000 / 139' }}
      decoding="async"
    />
  )
}
